### ISSUE TITLE
Nest feature extension

### ISSUE THREAD

**Issue by maikbooehme** [foxthefox/ioBroker.nest#1]
Hello,

would it be possible to extent the adapter to read out all values from the Nest Protect device ?

Best regards
Maik

**Comment by foxthefox** [comment]
I haven't really started with the adapter development, so it is right now only a skeleton.
First version should contain the thermostat.

**Comment by foxthefox** [comment]
I have started working on it.

**Comment by foxthefox** [comment]
Version 0.0.1 is released with readings for thermostat, camera and protect.
